### PR TITLE
Subgraph

### PR DESCRIPTION
**Pull request by jpfairbanks**
easy to use function `function inducedsubgraph(g::AbstractGraph, iter)` which returns the new graph and the vertex name map as a Dict.

worker function for filtering that does not allocate any temporaries.
`@doc "inplace filtering for preallocated output, edge iterable, vertex mapping" ->
function inducedsubgraph!(h::AbstractGraph, edges, newvid)`

### CODE REVIEW

**Comment by sbromberger** [comment]
This is great - thanks very much. Could we put this in operators.jl, though, and just call the functions "subgraph"?

**Comment by jpfairbanks** [comment]
Yes it can go in operators.

From wolfram mathworld: A vertex-induced subgraph (sometimes simply called an "induced subgraph") is a subset of the vertices of a graph G together with any edges whose endpoints are both in this subset. 
http://mathworld.wolfram.com/Vertex-InducedSubgraph.html

In the future we can support "graph minor" where the vertices are collapsed into each other by "edge contraction" http://mathworld.wolfram.com/GraphMinor.html although I don't have time to implement graph minor like i just did with induced subgraph.

**Comment by sbromberger** [comment]
OK - move to operators, keep the name :) But let's figure out why Travis is failing first.

**Comment by sbromberger** [comment]
ah, the @doc. Perhaps just leave it as a comment for now?

**Comment by jpfairbanks** [comment]
I used @doc so it didn't work on 0.3. I only use 0.4 locally. Either a version check or `using Docile`.

**Comment by jpfairbanks** [comment]
ok that's fine too but then we need to add it to doc/somewhere to get it in read the docs

**Comment by sbromberger** [comment]
I'll put it in RTD in a new commit. No worries.

**Comment by jpfairbanks** [comment]
i think i beat you to it?

**Comment by sbromberger** [comment]
Hah. ok. One other thing - does it make sense to test iter against g? that is, error if any element of iter > nv(g)?

**Comment by jpfairbanks** [comment]
you won't get an error if you don't. when iterating over the edges you will never try that vertex.

I'm inclined to follow the philosophy of handling argument diversity in the caller. We don't know how the iterable will be generated.

**Comment by sbromberger** [comment]
Yup, I see it (and agree with your philosophy). Will merge once travis comes back green - thanks :)

**Comment by sbromberger** [comment]
(disclaimer: agree with your philosophy except for add_edge!, where I error if the edge already exists.)

**Comment by sbromberger** [comment]
BTW: thanks for this. I can't wait to try it out!

**Comment by sbromberger** [comment]
Oh - one other thing (post merge): is this intended to work for directed graphs as well?

If so, it needs a change:

```
julia> g = DiGraph(100,200)
{100, 200} directed graph

julia> h = inducedsubgraph(g,[1,2,3,4])
({4, 0} undirected graph,Dict{Any,Any}(4=>4,2=>2,3=>3,1=>1))
```

If not, it needs to a change to only accept Graph (instead of AbstractGraph).

**Comment by jpfairbanks** [comment]
fixed it pretty cool that typeof(g)(n) works to construct the same type of
g. I just guessed that it would work and it did.

**Comment by sbromberger** [comment]
Better way to do that is as follows:

```
function inducedsubgraph{T<:AbstractGraph}(g::T, iter)
    n = length(iter)
    h = T(n)
...
```

Let me code something up. I also think we can get more efficiency by using finclist of the original graph. I'll do some testing.

**Pull request merged**
